-- CREATE DATABASE
CREATE DATABASE TT_QLKHO
GO
-- USE Database
USE TT_QLKHO
GO

------------------------------------------------- CREATE TABLE--------------------------------------------------------
CREATE TABLE NHANVIEN
(
	MA_NV INT IDENTITY(1,1) NOT NULL,
	TEN_NV NVARCHAR(100),
	SDT_NV INT,
	EMAIL_NV CHAR(100),

	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MA_NV)
)
GO

CREATE TABLE NHACUNGCAP
(
	MA_NCC INT IDENTITY(1,1) NOT NULL,
	TEN_NCC NVARCHAR(100),
	DIACHI_NCC NVARCHAR(100),
	SDT_NCC INT,
	WEBSITE_NCC CHAR(50),

	CONSTRAINT PK_NHACUNGCAP PRIMARY KEY (MA_NCC)
)
GO

CREATE TABLE PHIEUXUAT
(
	MA_PX INT IDENTITY(1,1) NOT NULL,
	MA_NV INT , 
	NGAYXUAT DATE DEFAULT GETDATE(),

	CONSTRAINT PK_PHIEUXUAT PRIMARY KEY (MA_PX),
	CONSTRAINT PK_NHANVIEN_FK_PHIEUXUAT FOREIGN KEY (MA_NV) REFERENCES dbo.NHANVIEN(MA_NV)
)
GO

CREATE TABLE PHIEUNHAP
(
	MA_PN INT IDENTITY(1,1) NOT NULL,
	MA_NV INT,
	MA_NCC INT,
	NGAYNHAP DATE DEFAULT GETDATE(),

	CONSTRAINT PK_PHIEUNHAP PRIMARY KEY (MA_PN),
	CONSTRAINT PK_NHANVIEN_FK_PHIEUNHAP FOREIGN KEY (MA_NV) REFERENCES dbo.NHANVIEN(MA_NV),
	CONSTRAINT PK_NHACUNGCAP_FK_PHIEUNHAP FOREIGN KEY (MA_NCC) REFERENCES dbo.NHACUNGCAP(MA_NCC)
)

CREATE TABLE SANPHAM
(
	MA_SP INT IDENTITY(1,1) NOT NULL,
	TEN_SP NVARCHAR(100),
	MA_NCC INT,
	THONGSO_KT NVARCHAR(100),
	GIA FLOAT,
	SOLUONG INT,

	CONSTRAINT PK_SANPHAM PRIMARY KEY (MA_SP),
	CONSTRAINT PK_NHACUNGCAP_FK_SANPHAM FOREIGN KEY (MA_NCC) REFERENCES dbo.NHACUNGCAP(MA_NCC)
)
GO

CREATE TABLE CT_PHIEUNHAP
(
	MA_CTPN INT IDENTITY(1,1) NOT NULL,
	MA_PN INT ,
	MA_SP INT ,
	SOLUONG INT,
	DONGIA FLOAT,

	CONSTRAINT PK_CT_PHIEUNHAP PRIMARY KEY(MA_CTPN),
	CONSTRAINT PK_PHIEUNHAP_FK_CT_PHIEUNHAP FOREIGN KEY (MA_PN) REFERENCES dbo.PHIEUNHAP,
	CONSTRAINT PK_SANPHAM_FK_CT_PHIEUNHAP FOREIGN KEY (MA_SP) REFERENCES dbo.SANPHAM
)

CREATE TABLE CT_PHIEUXUAT
(
	MA_CTPX INT IDENTITY(1,1) NOT NULL,
	MA_PX INT,
	MA_SP INT,
	SOLUONG INT,
	DONGIA FLOAT,

	CONSTRAINT PK_CT_PHIEUXUAT PRIMARY KEY(MA_CTPX),
	CONSTRAINT PK_PHIEUXUAT_FK_CT_PHIEUXUAT FOREIGN KEY (MA_PX) REFERENCES dbo.PHIEUXUAT,
	CONSTRAINT PK_SANPHAM_FK_CT_PHIEUXUAT FOREIGN KEY (MA_SP) REFERENCES dbo.SANPHAM
)
GO

-----------------------------------------------------------BẢNG NHÂN VIÊN--------------------------------------------------------------------------
-------TẠO PROC GETALL
CREATE PROC SP_NHANVIEN_GETALL
AS
BEGIN
	SELECT MA_NV, TEN_NV, SDT_NV, EMAIL_NV
	FROM dbo.NHANVIEN
END
GO

EXEC dbo.SP_NHANVIEN_GETALL
GO

-------TẠO PROC INSERT
CREATE PROC SP_NHANVIEN_INSERT
	@TENNV NVARCHAR(100),
	@SDT INT,
	@EMAIL CHAR(100)
AS
BEGIN
	INSERT INTO dbo.NHANVIEN( TEN_NV, SDT_NV, EMAIL_NV )
	VALUES  ( @TENNV, -- TEN_NV - nvarchar(100)
	          @SDT, -- SDT_NV - int
	          @EMAIL  -- EMAIL_NV - char(100)
	          )
END
GO

------TẠO PROC DELETE
CREATE PROC SP_NHANVIEN_DELETE
	@MANV INT
AS
BEGIN
	DELETE dbo.NHANVIEN WHERE MA_NV = @MANV
END
GO

------TẠO PROC UPDATE
CREATE PROC SP_NHANVIEN_UPDATE
	@MANV INT,
	@TENNV NVARCHAR(100),
	@SDT INT,
	@EMAIL CHAR(100)
AS
BEGIN
	UPDATE dbo.NHANVIEN
	SET TEN_NV = @TENNV, SDT_NV = @SDT, EMAIL_NV = @EMAIL
	WHERE MA_NV = @MANV
END
GO

---TẠO PROC SEARCH
CREATE PROC SP_NHANVIEN_SEARCH
	@SEARCHVALUE NVARCHAR(100)
AS
BEGIN
	SELECT MA_NV, TEN_NV, SDT_NV, EMAIL_NV
	FROM dbo.NHANVIEN
	WHERE (dbo.NHANVIEN.MA_NV LIKE N'%' + @SEARCHVALUE +'%')
		OR (dbo.NHANVIEN.TEN_NV LIKE N'%' + @SEARCHVALUE + '%')
		OR (dbo.NHANVIEN.SDT_NV LIKE N'%' + @SEARCHVALUE + '%')
		OR (dbo.NHANVIEN.EMAIL_NV LIKE N'%' + @SEARCHVALUE + '%')
END
GO
